In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.width', 5000)
pd.set_option('display.max_columns', 60)

In [3]:
df = pd.read_csv (r'C:\Users\user1\Desktop\EmployeeStatusReportTEST.csv')
df[:2]

   serviceid    branch contractterm    programmodel campus                  servicename  fundingSource  secondaryFundingSource  FundedBy_OtherSpecify  budgetcategory initiative budgetstatus budgetedstaff  totalinstructorExpenses StaffWorkEligibility ContractStatus  cityspanid                                             faults       roles        firstname  lastname                              email PayrollID Gender EEORace Disabled Veteran  hourlyrate  totalhoursavailable ContractSentDate  ... CPS Print CPS Emp ID CPS Clear CPS BG Status Exempt By ASM  ASM Print ASM Clear ASM BG Status  DCFS Rec DCFS Clear  DCFS BG Status     NSOPW     MVOAY PACR (IND) Contact Info Experience Form Education Form Social Media Policy Confidential   I9 Emp Handbook EEO - R-G EEO - V EEO - DS programspecialists programmanagers ContentArea SubContentArea  Category edocid
0    3708652  Downtown  Spring Only  Apprenticeship    NaN  ##Spring 2020 Test Activity            NaN                     NaN                    NaN             NaN        NaN          NaN           NaN                      NaN         Not Eligible     Incomplete  47734199.0  ; Confidential Missing; Contact Info Missing; ...  Instructor  Instructor Dana     Adams  dana.adams@afterschoolmatters.org       NaN    NaN     NaN      NaN     NaN         NaN                  0.0              NaN  ...  1/1/2099        NaN  1/1/2099          ; OK           NaN   1/1/2099  1/1/2099          ; OK  1/1/2099   1/1/2099            ; OK  1/1/2099  1/1/2099        NaN          NaN             NaN            NaN                 NaN          NaN  NaN          NaN       NaN     NaN      NaN                NaN             NaN        Arts     Visual Art  Painting  80981
1    3708652  Downtown  Spring Only  Apprenticeship    NaN  ##Spring 2020 Test Activity            NaN                     NaN                    NaN             NaN        NaN          NaN           NaN                      NaN         Not Eligible     Incomplete  46758971.0  ASM Pending; Confidential Missing; Contact Inf...  Instructor          Patrick  McCarthy                                  x       NaN    NaN     NaN      NaN     NaN         NaN                  0.0              NaN  ...       NaN        NaN       NaN    ; ; Exempt           1.0  3/16/2018       NaN   ; ; Pending       NaN        NaN     ; ; Missing       NaN       NaN        NaN          NaN             NaN            NaN                 NaN          NaN  NaN          NaN       NaN     NaN      NaN                NaN             NaN        Arts     Visual Art  Painting  80981

[2 rows x 66 columns]

In [4]:
df = df.replace(to_replace ='EbonÃ© Harden; Melissa Alvarez',
                 value ='Melissa Gracia')
df = df[df.servicename != '##Spring 2020 Test Activity']
df = df.replace(to_replace ='Melissa Alvarez',
                 value ='Melissa Gracia')

In [5]:
df = df.drop(['contractterm','programmodel', 'campus', 'fundingSource', 'secondaryFundingSource', 'FundedBy_OtherSpecify', 'budgetcategory', 'initiative', 'budgetstatus', 'budgetedstaff', 'totalinstructorExpenses', 'StaffWorkEligibility', 'PayrollID', 'Gender', 'EEORace', 'Disabled', 'Veteran', 'hourlyrate', 'totalhoursavailable', 'ContractSentDate', 'LastContactDate', 'ContractNotes', 'Signed Budget', 'Completion', 'MR Cert', 'MR Ack', 'CPS Print', 'CPS Emp ID', 'CPS Clear', 'CPS BG Status', 'Exempt By ASM', 'ASM Print', 'ASM Clear', 'ASM BG Status', 'DCFS Rec', 'DCFS Clear', 'DCFS BG Status', 'NSOPW', 'MVOAY', 'PACR (IND)', 'Contact Info', 'Experience Form', 'Education Form', 'Social Media Policy', 'Confidential', 'I9', 'Emp Handbook', 'EEO - R-G', 'EEO - V', 'EEO - DS', 'ContentArea', 'SubContentArea', 'Category', 'edocid'], axis =1)
df[:2]

   serviceid           branch servicename ContractStatus  cityspanid                                             faults       roles firstname lastname                        email programspecialists programmanagers
2    3430374  South/Southwest  A&A Sports       Complete   5372689.0                                                NaN  Instructor    Amanda  Leonard    mandysmith333@hotmail.com      Sheena Shukla  Melissa Gracia
3    3430374  South/Southwest  A&A Sports     Incomplete  34856449.0  ; Emp Handbook Expired; MR Ack Expired; PACR (...  Instructor   Sheldon  Wilkins  sheldonwilkins463@yahoo.com      Sheena Shukla  Melissa Gracia

In [6]:
df['staffname'] = df['lastname'].str.cat(df['firstname'],sep=", ")

In [7]:
df = df[['serviceid', 'branch', 'servicename', 'ContractStatus','cityspanid', 'faults', 'roles', 'staffname', 'programspecialists', 'programmanagers']]

In [8]:
not_external = ['MVOAY Expired', 'MVOAY Missing', 'NSOPW Missing', 'NSOPW Expired', 'CPS Exempt', 'MVOAY Expired;', 'MVOAY Missing;', 'NSOPW Expired;', 'NSOPW Missing;', 'CPS Exempt;']

In [9]:
pat = r'\b(?:{})\b'.format('|'.join(not_external))

In [10]:
pat

'\\b(?:MVOAY Expired|MVOAY Missing|NSOPW Missing|NSOPW Expired|CPS Exempt|MVOAY Expired;|MVOAY Missing;|NSOPW Expired;|NSOPW Missing;|CPS Exempt;)\\b'

In [11]:
df['faultsupdate'] = df['faults'].str.replace(pat, '').str.replace('I9', 'IZ')

In [12]:
df = df[['serviceid', 'branch', 'servicename', 'ContractStatus','cityspanid', 'faultsupdate', 'roles', 'staffname', 'programspecialists', 'programmanagers']]
df

     serviceid           branch                                     servicename ContractStatus  cityspanid                                       faultsupdate                            roles             staffname programspecialists programmanagers
2      3430374  South/Southwest                                      A&A Sports       Complete   5372689.0                                                NaN                       Instructor       Leonard, Amanda      Sheena Shukla  Melissa Gracia
3      3430374  South/Southwest                                      A&A Sports     Incomplete  34856449.0  ; Emp Handbook Expired; MR Ack Expired; PACR (...                       Instructor      Wilkins, Sheldon      Sheena Shukla  Melissa Gracia
4      3430410  North/Northwest              Advanced Art @ Phoenix Military HS       Complete  35478895.0                                                NaN                       Instructor      McElgunn, Daniel    Randiss Hopkins  Chris Nergaard
5      3430410  North/Northwest              Advanced Art @ Phoenix Military HS       Complete  46802291.0                                                NaN                       Instructor      Williams, Jamaal    Randiss Hopkins  Chris Nergaard
6      3520620  South/Southwest                     Advanced Baseball @ Solorio     Incomplete  40901610.0  ; ASM Missing; Education Form Missing; Emp Han...                       Instructor        Bingham, Kevin     Karina Esparza  Melissa Gracia
..         ...              ...                                             ...            ...         ...                                                ...                              ...                   ...                ...             ...
441    3432389         Downtown                     Yoga (Downtown Gallery 37)        Complete  46819111.0                                                NaN                       Instructor        Oakley, Candis        Kasumi Kato  Rashaan Meador
442    3432404  South/Southwest  You Got Served Culinary Program@ Mandrake Park       Complete  44831526.0                                                     Independent Liaison; Instructor        Brown, Porscha    Nubia Henderson  Melissa Gracia
443    3432413  North/Northwest            Young Leaders Empowerment Initiative     Incomplete  47727143.0                            ; Signed Budget Missing                       Instructor       Gordon, Aveiyah      Claire Meyers  Marchae Miller
444    3432413  North/Northwest            Young Leaders Empowerment Initiative     Incomplete  46911973.0                            ; Signed Budget Missing                       Instructor  Howard, Aniyah (Orr)      Claire Meyers  Marchae Miller
445    3432413  North/Northwest            Young Leaders Empowerment Initiative     Incomplete  46695415.0                            ; Signed Budget Missing  Independent Liaison; Instructor        Orr, Angelique      Claire Meyers  Marchae Miller

[444 rows x 10 columns]

In [13]:
df = df.fillna('nothing')

In [14]:
cannot_work = ['ASM Pending', 'CPS Pending,', 'DCFS Pending', 'ASM Missing', 'CPS Missing', 'IZ Missing', 'DCFS Missing', 'MR Cert Missing']
missing_items = ['Confidential Missing', 'Contact Info Missing', 'Education Form Missing', 'Emp Handbook Missing', 'Experience Form Missing', 'MR Ack Missing', 'MR Ack Missing', 'MR Ack Expired', 'PACR (IND) Missing', 'Signed Budget Missing', 'Social Media Policy Missing']

In [15]:
def match_list(faultsupdate, staffname):
    k = ([cannot_work[cannot_work.index(s)] for s in cannot_work if s in faultsupdate]) or ([s for s in cannot_work if s in faultsupdate])
    return k[0] if k else ''

df['notworkstatus'] = df.apply(lambda x: match_list(x['faultsupdate'], x['staffname']), axis=1)

In [16]:
cw_cleanup = r'\b(?:{})\b'.format('|'.join(cannot_work))

In [17]:
df['notworkstatus'] = df['notworkstatus'].str.replace(cw_cleanup, 'Cannot Start - See Details for Missing Items')

In [18]:
df[:4]

   serviceid           branch                         servicename ContractStatus   cityspanid                                       faultsupdate       roles         staffname programspecialists programmanagers notworkstatus
2    3430374  South/Southwest                          A&A Sports       Complete  5.37269e+06                                            nothing  Instructor   Leonard, Amanda      Sheena Shukla  Melissa Gracia
3    3430374  South/Southwest                          A&A Sports     Incomplete  3.48564e+07  ; Emp Handbook Expired; MR Ack Expired; PACR (...  Instructor  Wilkins, Sheldon      Sheena Shukla  Melissa Gracia
4    3430410  North/Northwest  Advanced Art @ Phoenix Military HS       Complete  3.54789e+07                                            nothing  Instructor  McElgunn, Daniel    Randiss Hopkins  Chris Nergaard
5    3430410  North/Northwest  Advanced Art @ Phoenix Military HS       Complete  4.68023e+07                                            nothing  Instructor  Williams, Jamaal    Randiss Hopkins  Chris Nergaard

In [19]:
def match_list_canworkmiss(faultsupdate, staffname):
    k = ([missing_items[missing_items.index(s)] for s in missing_items if s in faultsupdate]) or ([s for s in missing_items if s in faultsupdate])
    return k[0] if k else ''

df['workstatuscanworkmiss'] = df.apply(lambda x: match_list_canworkmiss(x['faultsupdate'], x['staffname']), axis=1)

In [20]:
miss_cleanup = r'\b(?:{})\b'.format('|'.join(missing_items))

In [21]:
df['workstatuscanworkmiss'] = df['workstatuscanworkmiss'].str.replace(miss_cleanup, 'Can Start with Missing Items - See Details for Missing Items')

In [22]:
df[:4]

   serviceid           branch                         servicename ContractStatus   cityspanid                                       faultsupdate       roles         staffname programspecialists programmanagers notworkstatus                              workstatuscanworkmiss
2    3430374  South/Southwest                          A&A Sports       Complete  5.37269e+06                                            nothing  Instructor   Leonard, Amanda      Sheena Shukla  Melissa Gracia
3    3430374  South/Southwest                          A&A Sports     Incomplete  3.48564e+07  ; Emp Handbook Expired; MR Ack Expired; PACR (...  Instructor  Wilkins, Sheldon      Sheena Shukla  Melissa Gracia                Can Start with Missing Items - See Details for...
4    3430410  North/Northwest  Advanced Art @ Phoenix Military HS       Complete  3.54789e+07                                            nothing  Instructor  McElgunn, Daniel    Randiss Hopkins  Chris Nergaard
5    3430410  North/Northwest  Advanced Art @ Phoenix Military HS       Complete  4.68023e+07                                            nothing  Instructor  Williams, Jamaal    Randiss Hopkins  Chris Nergaard

In [23]:
no_working = ['Cannot Start - See Details for Missing Items']
yes_working_but = ['Can Start with Missing Items - See Details for Missing Items']

In [24]:
df['Can Staff Start Work?'] = np.where(df['notworkstatus'].str.contains('|'.join(no_working)),
        'NO CANNOT WORK - see details',
         np.where(df['workstatuscanworkmiss'].str.contains('|'.join(yes_working_but)),
             'Yes but missing items -- see details',
             'Yes can work, nothing else needed this session'))

In [25]:
df

     serviceid           branch                                     servicename ContractStatus   cityspanid                                       faultsupdate                            roles             staffname programspecialists programmanagers                                 notworkstatus                              workstatuscanworkmiss                           Can Staff Start Work?
2      3430374  South/Southwest                                      A&A Sports       Complete  5.37269e+06                                            nothing                       Instructor       Leonard, Amanda      Sheena Shukla  Melissa Gracia                                                                                                   Yes can work, nothing else needed this session
3      3430374  South/Southwest                                      A&A Sports     Incomplete  3.48564e+07  ; Emp Handbook Expired; MR Ack Expired; PACR (...                       Instructor      Wilkins, Sheldon      Sheena Shukla  Melissa Gracia                                                Can Start with Missing Items - See Details for...            Yes but missing items -- see details
4      3430410  North/Northwest              Advanced Art @ Phoenix Military HS       Complete  3.54789e+07                                            nothing                       Instructor      McElgunn, Daniel    Randiss Hopkins  Chris Nergaard                                                                                                   Yes can work, nothing else needed this session
5      3430410  North/Northwest              Advanced Art @ Phoenix Military HS       Complete  4.68023e+07                                            nothing                       Instructor      Williams, Jamaal    Randiss Hopkins  Chris Nergaard                                                                                                   Yes can work, nothing else needed this session
6      3520620  South/Southwest                     Advanced Baseball @ Solorio     Incomplete  4.09016e+07  ; ASM Missing; Education Form Missing; Emp Han...                       Instructor        Bingham, Kevin     Karina Esparza  Melissa Gracia  Cannot Start - See Details for Missing Items  Can Start with Missing Items - See Details for...                    NO CANNOT WORK - see details
..         ...              ...                                             ...            ...          ...                                                ...                              ...                   ...                ...             ...                                           ...                                                ...                                             ...
441    3432389         Downtown                     Yoga (Downtown Gallery 37)        Complete  4.68191e+07                                            nothing                       Instructor        Oakley, Candis        Kasumi Kato  Rashaan Meador                                                                                                   Yes can work, nothing else needed this session
442    3432404  South/Southwest  You Got Served Culinary Program@ Mandrake Park       Complete  4.48315e+07                                                     Independent Liaison; Instructor        Brown, Porscha    Nubia Henderson  Melissa Gracia                                                                                                   Yes can work, nothing else needed this session
443    3432413  North/Northwest            Young Leaders Empowerment Initiative     Incomplete  4.77271e+07                            ; Signed Budget Missing                       Instructor       Gordon, Aveiyah      Claire Meyers  Marchae Miller                                                Can Start with Missing Items - See Details for...            Yes but missing items -- see details
444    3432413  North/Northwest            Young Leaders Empowerment Initiative     Incomplete   4.6912e+07                            ; Signed Budget Missing                       Instructor  Howard, Aniyah (Orr)      Claire Meyers  Marchae Miller                                                Can Start with Missing Items - See Details for...            Yes but missing items -- see details
445    3432413  North/Northwest            Young Leaders Empowerment Initiative     Incomplete  4.66954e+07                            ; Signed Budget Missing  Independent Liaison; Instructor        Orr, Angelique      Claire Meyers  Marchae Miller                                                Can Start with Missing Items - See Details for...            Yes but missing items -- see details

[444 rows x 13 columns]